name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate dummies
        run: |
          mkdir "./deploy/"
          find "./images/" -type f -exec bash -c '
            DEPLOY_PATH=$(dirname "./deploy/$1");
            DEPLOY_NAME=$(basename "$1")
            if [ ! -d $DEPLOY_PATH ]; then
                mkdir -p "$DEPLOY_PATH"
            fi
            touch "$DEPLOY_PATH/$DEPLOY_NAME"
          ' _ {} \;
          rm -rf "./images/"
          mv "./deploy/images/" "./images"
      - name: Deploy
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Deploying to deploy from @ ${{ github.sha }} 🚀
          branch: deploy
          force: true
