name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - shell: bash
        run: |
          mkdir "./deploy/"
          find "./images/" -type f -exec bash -c '
            DEPLOY_PATH=$(dirname "./deploy/$1");
            DEPLOY_NAME=$(basename "$1")
            if [ ! -d $DEPLOY_PATH ]; then
                mkdir -p "$DEPLOY_PATH"
            fi
            touch "$DEPLOY_PATH/$DEPLOY_NAME"
          ' _ {} \;
      - uses: EndBug/add-and-commit@v7
        with:
          add: ./images/
          remove: '["'./github/'", "./images/"]'
          author_name: GitHub Action
          author_email: action@github.com
          branch: deploy
          branch_mode: create
      # - name: Commit changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add "./index.d.ts"
      #     git commit -m "chore: Update natives/index.d.ts" -m "Co-authored-by: $(git diff-tree ${{ github.sha }} --pretty='format:%an <%ae>' -s)"
      # - name: Push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
